export const MY_VIDEO_STREAM = "MY_VIDEO_STREAM";
export const MY_AUDIO_STREAM = "MY_AUDIO_STREAM";
export const JOIN_ROOM = "JOIN_ROOM";
export const ADD_VIDEO_STREAM = "ADD_VIDEO_STREAM";
export const ADD_AUDIO_STREAM = "ADD_AUDIO_STREAM";
export const ADD_REMOTE_VIDEO_STREAM = "ADD_REMOTE_VIDEO_STREAM";
export const ADD_REMOTE_AUDIO_STREAM = "ADD_REMOTE_AUDIO_STREAM";
export const AUDIO = "AUDIO";
export const VIDEO = "VIDEO";
export const FETCH_ROOM_LISTENERS = "FETCH_ROOM_LISTENERS";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
export const REMOVE_VIDEO_STREAM = "REMOVE_VIDEO_STREAM";

export const FLUSH = "FLUSH";
export const LISTENER = "LISTENER";
export const STREAMER = "STREAMER";
